#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────
# deploy.sh — Tag and release a new version of transfer.sh
#
# Usage:
#   ./scripts/deploy.sh           # auto-increment patch (v1.0.1 -> v1.0.2)
#   ./scripts/deploy.sh v1.2.0    # explicit version
#
# Steps:
#   1. Validate version argument or auto-increment patch
#   2. Check for clean working tree and current branch
#   3. Run go vet
#   4. Run go test -race
#   5. Generate CHANGELOG entry from git log (Claude CLI optional)
#   6. Commit CHANGELOG.md if it changed
#   7. Create annotated git tag with release notes
#   8. Push commit + tag to origin
#   9. Create GitHub Release (triggers GHCR build)
#  10. Watchtower picks up the new image on the server
# ─────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── 1. Resolve current and target version ─────────────────
VERSION_ARG="${1:-}"

# Latest tag, e.g. "v1.0.1". Empty if no tag yet.
CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
CURRENT_VERSION="${CURRENT_TAG#v}"

if [[ -z "$VERSION_ARG" ]]; then
  if [[ -z "$CURRENT_VERSION" ]]; then
    error "No previous tag found. Pass an explicit version, e.g. v0.1.0"
  fi
  IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
  PATCH=$((PATCH + 1))
  SEMVER="${MAJOR}.${MINOR}.${PATCH}"
  TAG="v${SEMVER}"
  info "No version specified - auto-incrementing patch"
elif [[ "$VERSION_ARG" =~ ^v?([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
  SEMVER="${BASH_REMATCH[1]}"
  TAG="v${SEMVER}"
else
  error "Invalid version format: $VERSION_ARG (expected vX.Y.Z)"
fi

info "Current version: ${CURRENT_TAG:-none}"
info "New version:     ${TAG}"
echo ""

# Refuse to release a tag that already exists.
if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null; then
  error "Tag ${TAG} already exists"
fi

# ── 2. Working tree + branch ──────────────────────────────
if [[ -n "$(git status --porcelain)" ]]; then
  error "Working tree is not clean. Commit or stash your changes first."
fi

BRANCH=$(git branch --show-current)
if [[ "$BRANCH" != "main" ]]; then
  warn "You are on branch '${BRANCH}', not 'main'. Continue? (y/N)"
  read -r CONFIRM
  [[ "$CONFIRM" =~ ^[yY]$ ]] || exit 0
fi
ok "Working tree is clean (branch: ${BRANCH})"

# ── 3. go vet ─────────────────────────────────────────────
info "Running go vet..."
go vet ./...
ok "go vet passed"

# ── 4. go test ────────────────────────────────────────────
info "Running go test -race..."
go test -race ./...
ok "tests passed"

# ── 5. Generate CHANGELOG entry ───────────────────────────
info "Collecting commits since ${CURRENT_TAG:-the beginning of history}..."

if [[ -n "$CURRENT_TAG" ]]; then
  COMMIT_RANGE="${CURRENT_TAG}..HEAD"
else
  COMMIT_RANGE="HEAD"
fi

COMMITS=""
while IFS= read -r line; do
  msg="${line#* }"
  case "$msg" in
    Release\ v*|Merge\ *) continue ;;
  esac
  COMMITS+="${msg}"$'\n'
done < <(git log "$COMMIT_RANGE" --oneline --no-merges 2>/dev/null || git log --oneline --no-merges)

if [[ -z "$(echo "$COMMITS" | tr -d '[:space:]')" ]]; then
  warn "No new commits since ${CURRENT_TAG}. Aborting."
  exit 1
fi

TODAY=$(date +%Y-%m-%d)

# Use Claude CLI to summarise commits if available; fall back to a raw list.
CHANGELOG_BODY=""
if command -v claude &> /dev/null; then
  info "Summarising commits with Claude..."
  PROMPT="Du schreibst den Changelog für transfer.sh, ein selbst-gehostetes File-Sharing-Tool.

Schreibe basierend auf diesen Git-Commits einen kurzen, technisch-faktischen Changelog-Abschnitt auf Englisch.

Commits:
${COMMITS}

Regeln:
- Verwende diese Kategorien (nur wenn passend, leere weglassen): ### Added, ### Changed, ### Fixed, ### Removed
- Jeder Eintrag beginnt mit '- ' und beschreibt eine konkrete Aenderung
- Faktisch und knapp, kein Marketing-Text, keine Emojis
- Maximal 8 Eintraege insgesamt; trivial commits (typos, formatting, dependency bumps ohne Effekt) zusammenfassen oder weglassen
- Kein einleitender Text, nur die Kategorien mit Eintraegen
- Beispiel guter Eintrag: '- Auto-create the temp folder on startup so any TEMP_PATH value works'"

  CHANGELOG_BODY=$(echo "$PROMPT" | claude --print 2>/dev/null || echo "")
fi

if [[ -n "$CHANGELOG_BODY" ]]; then
  CHANGELOG_ENTRY="## [${SEMVER}] - ${TODAY}"$'\n\n'"${CHANGELOG_BODY}"
  ok "Changelog generated by Claude"
else
  CHANGELOG_ENTRY="## [${SEMVER}] - ${TODAY}"$'\n\n'"### Changes"
  while IFS= read -r line; do
    [[ -n "$line" ]] && CHANGELOG_ENTRY+=$'\n'"- ${line}"
  done <<< "$COMMITS"
  warn "Falling back to raw commit list"
fi

# Insert into CHANGELOG.md after [Unreleased] header.
if [[ -f CHANGELOG.md ]]; then
  TEMP_FILE=$(mktemp)
  ENTRY_FILE=$(mktemp)
  echo "$CHANGELOG_ENTRY" > "$ENTRY_FILE"
  awk '
    /^## \[Unreleased\]/ {
      print $0
      print ""
      while ((getline line < "'"$ENTRY_FILE"'") > 0) print line
      print ""
      skip = 1
      next
    }
    skip && /^## \[/ {
      skip = 0
    }
    !skip { print }
  ' CHANGELOG.md > "$TEMP_FILE"
  mv "$TEMP_FILE" CHANGELOG.md
  rm -f "$ENTRY_FILE"
  ok "CHANGELOG.md updated"
else
  cat > CHANGELOG.md <<EOF
# Changelog

All notable changes to this project are documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)
and the project adheres to [Semantic Versioning](https://semver.org/).

## [Unreleased]

${CHANGELOG_ENTRY}
EOF
  ok "CHANGELOG.md created"
fi

echo ""
echo -e "${CYAN}-- Changelog Entry --------------------${NC}"
echo "$CHANGELOG_ENTRY"
echo -e "${CYAN}---------------------------------------${NC}"
echo ""

# ── 6. Commit CHANGELOG ───────────────────────────────────
if [[ -n "$(git status --porcelain CHANGELOG.md)" ]]; then
  info "Committing CHANGELOG.md..."
  git add CHANGELOG.md
  git commit -m "$(cat <<EOF
Release ${TAG}

- Update CHANGELOG with release notes
EOF
)"
  ok "Committed"
else
  warn "CHANGELOG.md unchanged - skipping commit"
fi

# ── 7. Annotated tag ──────────────────────────────────────
info "Creating tag ${TAG}..."
git tag -a "$TAG" -m "$(cat <<EOF
Release ${TAG}

${CHANGELOG_ENTRY}
EOF
)"
ok "Tag ${TAG} created"

# ── 8. Push branch + tag ──────────────────────────────────
info "Pushing to origin..."
git push origin "$BRANCH"
git push origin "$TAG"
ok "Pushed commit and tag"

# ── 9. GitHub Release (gh CLI) ────────────────────────────
if command -v gh &> /dev/null; then
  info "Creating GitHub Release..."
  gh release create "$TAG" \
    --title "Release ${TAG}" \
    --notes "$CHANGELOG_ENTRY" \
    --latest
  ok "GitHub Release created - GHCR build will start automatically"
else
  warn "gh CLI not installed - create the release manually on GitHub"
  REMOTE_PATH=$(git remote get-url origin | sed -e 's|.*github.com[:/]||' -e 's|\.git$||')
  warn "  https://github.com/${REMOTE_PATH}/releases/new?tag=${TAG}"
fi

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Release ${TAG} complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "  GHCR multi-arch image will be built by GitHub Actions."
echo "  Watchtower on the server will auto-update the running container."
echo ""
