name: test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    name: Test (Go ${{ matrix.go_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.23', '1.24']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config .golangci.yml
